pipeline:
    name: CD Feature Branch
    identifier: CD_Feature_Branch
    allowStageExecutions: false
    projectIdentifier: goHelloWorld
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: deploy feature branch
              identifier: deploy_feature_branch
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: goHelloWorld
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: deployment
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: goHelloWorld
                                                    gitFetchType: Branch
                                                    paths:
                                                        - deployment.yaml
                                                    branch: main
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: ValuesFeatureBranch
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: goHelloWorld
                                                    gitFetchType: Branch
                                                    paths:
                                                        - valuesFeatureBranch.yaml
                                                    branch: main
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: org.Docker_Hub
                                          imagePath: rmailaender/gohelloworldserver
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: Test
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: org.GKEdefault
                              namespace: goserver-featurebranch
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
