apiVersion: v1
kind: Service
metadata:
  name: {{.Values.prefix}}go-hello-world-svc
  labels:
    app: {{.Values.prefix}}gohelloworld
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{.Values.dnsName}}
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: {{.Values.nodePort}}
  selector:
    app: {{.Values.prefix}}gohelloworldpod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.prefix}}go-hello-world-deployment
  labels:
    app: {{.Values.prefix}}gohelloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.prefix}}gohelloworldpod
  template:
    metadata:
      labels:
        app: {{.Values.prefix}}gohelloworldpod
    spec:
      containers:
      - name: {{.Values.prefix}}gopod
        image: {{.Values.image}}
        ports:
        - containerPort: 8080