pipeline:
    name: CI_test
    identifier: CI_test
    projectIdentifier: PaaS_CI
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: vsqdisqo
                repoName: goHelloWorldServer
                build: <+input>
    stages:
        - stage:
              name: Build Test and Push
              identifier: Build_Test_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: cidelegate
                          namespace: harness-delegate-ng
                          automountServiceAccountToken: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Run Unit Tests
                                identifier: Run_Unit_Tests
                                spec:
                                    connectorRef: account.Jfrog_Artifactory
                                    image: artifactory.disqotech.com/docker-local/golang:1.17
                                    shell: Sh
                                    command: |
                                        go get gotest.tools/gotestsum
                                        gotestsum --format=standard-verbose --junitfile unit-tests.xml || true
                                        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "*.xml"
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and Push Image to Artifactory
                                identifier: Build_and_Push_Image_to_Artifactory
                                spec:
                                    connectorRef: account.Jfrog_Artifactory
                                    repo: https://artifactory.disqotech.com/artifactory/docker_harness/
                                    tags:
                                        - <+pipeline.sequenceId>
        - stage:
              name: Run Integration Test
              identifier: Run_Integration_Test
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: Build_Test_and_Push
                  serviceDependencies:
                      - identifier: Run_Hello_World_Server
                        name: Run Hello World Server
                        type: Service
                        spec:
                            connectorRef: account.Jfrog_Artifactory
                            image: https://artifactory.disqotech.com/artifactory/docker_harness/<+pipeline.sequenceId>
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test connection to server
                                identifier: test_connection_to_server
                                spec:
                                    connectorRef: account.harnessImage
                                    image: curlimages/curl:7.73.0
                                    shell: Sh
                                    command: |-
                                        sleep 10
                                        curl localhost:8080
                                        curl localhost:8080?Hello!_this_is_harness_ci!
